services:
  frontend:
    build: ./frontend
    container_name: laboratorio-frontend
    expose:
      - "80"
    networks:
      - laboratorio_net

  backend:
    build: ./backend
    container_name: laboratorio-backend
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - laboratorio_net

  nginx:
    image: nginx:latest
    container_name: laboratorio-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - laboratorio_net

  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - laboratorio_net
    restart: unless-stopped

networks:
  laboratorio_net:
    driver: bridge
